kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  x509:
    clientCAFile: /var/lib/kubernetes/ca.pem
  anonymous:
    enabled: false
cgroupDriver: systemd
clusterDNS:
  - 172.30.0.10
clusterDomain: cluster.local
serializeImagePulls: false
systemReserved:
  cpu: 500m
  memory: 500Mi
